source 'https://rubygems.org'
ruby '2.6.3'
gem 'foreman'
gem "rack", ">= 2.0.6"
gem 'sinatra', '~> 2.0'
gem 'thin', '~> 1.7'
gem 'sinatra-contrib'
gem 'json'
gem 'activesupport'
gem 'log4r'
gem 'line-bot-api'
gem 'httpclient'
gem 'weighted_randomizer'
gem 'mechanize', ">= 2.7.6"
gem 'parallel'
gem 'url_expander'
gem 'mongo'