source 'https://rubygems.org'
ruby '2.3.1'
gem 'foreman'
gem 'rack'
gem 'sinatra'
gem 'thin', '~> 1.6', '>= 1.6.3'
gem 'sinatra-contrib'
gem 'json'
gem 'activesupport'
gem 'log4r'
gem 'line-bot-api'
gem 'httpclient'
gem 'weighted_randomizer'
gem 'mechanize'
